### ISSUE TITLE
Editing and Saving Jenkins config settings causes Datadog agent to stop reporting events 

### ISSUE THREAD

**Issue by dbsanfte** [DataDog/jenkins-datadog-plugin#101]
Every time I edit and save global settings in Jenkins, the Datadog agent on the master note simply stops reporting Jenkins events. Nothing will get it to resume reporting build events except restarting the Jenkins server.

Anyone else seeing this issue?

Jenkins 2.60.1 here running in Docker.

**Comment by sjenriquez** [comment]
@dbsanfte Thank you for reporting this, we'll take a look.

**Comment by DanielRedOak** [comment]
Were seeing issues with the DD plugin as well. No matter what I do, I can't seem to get it to report anything back.  Config checks out and API key test is successful. Any updates or information is greatly appreciated

**Comment by morlajb** [comment]
which Datadog plugin  version are you using ?

**Comment by scott-estes** [comment]
same issue here, Jenkins version 2.7.4.

I downgraded to 0.5.7, but now since we use pipelines I'm hitting the job.duration issue that was fixed in 0.6.1

Is there a timeline for getting this issue resolved?

**Comment by amitkumarjha** [comment]
Any update on the fix, I am facing the same issue here.

**Comment by sjenriquez** [comment]
@amitkumarjha We are working to resolve this asap, sorry for the delay. To downgrade to 0.5.7 you can download the binary at http://updates.jenkins-ci.org/download/plugins/datadog/

Instructions for a manual install can be found at https://jenkins.io/doc/book/managing/plugins/#advanced-installation

Please reach out to support@datadoghq.com if you have any trouble.

**Comment by DanielRedOak** [comment]
Glad to hear, thanks for the update!

**Comment by sjenriquez** [comment]
v0.6.2 is now available in the Jenkins Update Center, thanks for you patience!
