### ISSUE TITLE
Empty whitelist does not permit all jobs

### ISSUE THREAD

**Issue by johnjmaguire** [DataDog/jenkins-datadog-plugin#102]
Plugin 0.6.1
Jenkins 2.60.3

Upon upgrading to 0.6.1 we found all metrics apart from `jenkins.queue.size` missing from DataDog. To enable metrics again we had to specify all job names in the whitelist. This should not be the case according to the docs.

Thanks

**Comment by sjenriquez** [comment]
Thanks for reporting this @johnjmaguire, we'll investigate further.
