### ISSUE TITLE
Allow adding custom tags per job

### ISSUE THREAD

**Issue by kbaltrinic** [DataDog/jenkins-datadog-plugin#11]
The simplest solution would be to add a configuration option to each jobs config page where an admin could enter in a set of tags to tag the job with.  However a static list of tags, while useful, is not sufficient for us.  

We us parameterized jobs extensively. For example the same job builds all of our dropwizard projects in different configuration such as snapshot builds, release, builds, builds targeting platform X, targeting platform Y, etc.  At the very least we would need to be able to specify that certain build parameters, or even certain environment variables, need to be set as the values of certain tags.  For example set the #release tag to the value of the $DO_RELEASE env variable, and the #project tag be set to something based on which git repository we built from.

One possibility that would provide for maximum flexibility would be to be able to read in a set of tag values from a specified file in the workspace.  This way we could use any sort of post build script to programmatically setup our tags.

**Comment by jshirley** [comment]
We also need this feature, is this something that we could contribute a patch to add support for?

**Comment by JohnLZeller** [comment]
We're planning to add this in the next version of the plugin. You're more than welcome to contribute a patch to add support for this! Just make a PR, and we can review any changes you make.
