### ISSUE TITLE
Support prefix for White/Blacklist

### ISSUE THREAD

**Issue by broom9** [DataDog/jenkins-datadog-plugin#113]
Hi there,

Can you consider to support to specify job name prefixes for white/black lists? Aka. exclude jobs in a "sandbox/" folder? Thanks.

Wei

**Comment by sjenriquez** [comment]
Hi @broom9, this could certainly be useful. It's not something we'll be working on in the immediate future, but feel free to submit a PR if you get started before we do. Thanks!
