### ISSUE TITLE
Having stage statistics

### ISSUE THREAD

**Issue by Tiagojdferreira** [DataDog/jenkins-datadog-plugin#114]
Currently it is possible to know if a job failed, but it would be interesting to know in what stage of the pipeline the job failed.

Example of use case:
Jenkins job is devided into the following stages:
- lint
- build
- test backend
- test frontend
- functional tests

Knowing that a job fails during build or during functional tests requires very different actions to fix.

**Comment by sjenriquez** [comment]
Hi @Tiagojdferreira, this sounds like a nice feature. It's not something we'll be working on in the immediate future, but feel free to submit a PR if you get started before we do. Thanks!

**Comment by gzussa** [comment]
This issue is duplicated now and is being discussed in https://github.com/DataDog/jenkins-datadog-plugin/issues/152. Closing this issue. @Tiagojdferreira If you have a simple pipeline script i could use to test, that would be great 😄
