### ISSUE TITLE
Add ability to customize build tags from groovy pipelines

### ISSUE THREAD

**Issue by deiwin** [DataDog/jenkins-datadog-plugin#115]
I need to change a tag value based on what triggered the build (i.e. what's the build cause). After a lot of tinkering, I'm doing something like this:
```groovy
def cause = 'something' // actually comes from currentBuild.rawBuild.getCause...
properties([
  [
    $class: 'DatadogJobProperty',
    tagProperties: "cause=${cause}"
  ]
])
```
And this sort of works, but isn't really reliable. It causes issues when multiple jobs run concurrently. The [**current** `DatadogJobProperty` value is used](https://github.com/DataDog/jenkins-datadog-plugin/blob/1c3744329ec118f2f62a8ec4b158cb493380e266/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java#L237-L238) whenever a build finishes. That means that if job A starts with cause "A" and job B starts with cause "B" before A finishes running, then both jobs will use the last `DatadogJobProperty` which has "B" configured as the cause.

I also tried the following, but this fails to set the value altogether. The tag ends up as `cause=_cause`.
```groovy
env.CAUSE = 'something' // actually comes from currentBuild.rawBuild.getCause...
properties([
  [
    $class: 'DatadogJobProperty',
    tagProperties: 'cause=${CAUSE}'
  ]
])
```

**Comment by sjenriquez** [comment]
Thanks for the request @deiwin, I'm keeping this issue open to track this enhancement request. It may not be something we'll work on in the immediate future, but feel free to submit a PR if you get to it before us, thanks!

**Comment by gzussa** [comment]
Related to https://github.com/DataDog/jenkins-datadog-plugin/issues/152 (except that it is when using the JenkinsFile rather then groovy scripts). Keeping this one out of the two since it has more details.

**Comment by gzussa** [comment]
https://github.com/DataDog/jenkins-datadog-plugin/pull/164

**Comment by gzussa** [comment]
Moving this issue to https://github.com/jenkinsci/datadog-plugin/issues/22 since we are in the process of archiving this repository.
