### ISSUE TITLE
Set dogstatsd endpoint in a dockerized environment

### ISSUE THREAD

**Issue by Geethree** [DataDog/jenkins-datadog-plugin#116]
Hey all I'm currently running jenkins in docker, with datadog also running in docker. Silly question, how do I set the dogstatsd endpoint to the appropriate container?

Do I set the `DOGSTATSD_HOST` environment variable in the jenkins container?

**Comment by sjenriquez** [comment]
Hi @Geethree, sorry for the delay! Currently, the `DogStatsD Host` endpoint is not configurable via an environment variable or Groovy script, you need to configure it manually in the Jenkins > configuration page.

If it helps, the default is set to `localhost:8125`.  I will leave this issue open for a possible future plugin enhancement.

**Comment by gzussa** [comment]
Hi @Geethree Thanks for opening this issue. I am currently working on some improvements that would get rid of DogStatsD all together - see https://github.com/DataDog/jenkins-datadog-plugin/pull/169. Hence solving your issue 😄 . I will keep this issue open until I release a new version.

**Comment by gzussa** [comment]
I reconsidered my previous decision and brought back DogStatsD into the mix. However now, you will be able to use either the HTTP Client or the DogStatsD client. Here is the related PR https://github.com/DataDog/jenkins-datadog-plugin/pull/183 (still WIP). I am also going to make it possible to configure the plugin using env variable in another PR. I will keep you updated.

**Comment by gzussa** [comment]
Heads up: We just release version [1.0.0](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-1.0.0). This is a major bump with backward incompatibility changes. See related [changelog](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/CHANGELOG.md#100--01-07-2020).
