### ISSUE TITLE
Add a tag for Node (slave) name

### ISSUE THREAD

**Issue by kbaltrinic** [DataDog/jenkins-datadog-plugin#12]
Based on [line 175](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadogbuildreporter/DatadogBuildListener.java#L175) it would seem this is already in place but we are not seeing any `node` tag and this would be very useful for us in alerting when a particular slave is having problems.

**Comment by kbaltrinic** [comment]
@JohnLZeller Any chance of getting this into that next release as well?  This is the one tag (beyond the hostname) that we really need presently to be able to truly track the health of our slaves.

**Comment by JohnLZeller** [comment]
@kbaltrinic we'll go ahead and add this in the next release

**Comment by JohnLZeller** [comment]
PR #17 should handle this, and it has been merged. It'll be included in 0.2.0 release (the next release)
