### ISSUE TITLE
Add Pipeline support for tag files in workspace

### ISSUE THREAD

**Issue by sjenriquez** [DataDog/jenkins-datadog-plugin#122]
We currently don't support the tags from workspace file for Pipeline jobs as noted in the readme.

**Comment by cjcdoomed** [comment]
You have a PR that supports this: https://github.com/DataDog/jenkins-datadog-plugin/pull/144
Can it be merged in?

**Comment by gzussa** [comment]
Migrating this issue to https://github.com/jenkinsci/datadog-plugin/issues/21. Closing it
