### ISSUE TITLE
Jobs not reporting to datadog once they are moved to a slave

### ISSUE THREAD

**Issue by leo-novu** [DataDog/jenkins-datadog-plugin#123]
We have a number of jobs that report back information to the Datadog server until we move them to a slave.  Once a label is added to have the job run on the slave the job no longer reports back to Datadog.  We are using the Amazon EC2 Container Service Cloud Jenkins plugin to spin up containers as slaves.

**Comment by sjenriquez** [comment]
Hi again @leo-novu, we are in the process of releasing v0.6.5 with a fix for a similar issue to what you are describing. I'm going to close this issue, but if you are still seeing any problems after upgrading please reach out to us at support@datadoghq.com so we can further assist. Thanks!
