### ISSUE TITLE
Have pipeline statistics

### ISSUE THREAD

**Issue by pgarbe** [DataDog/jenkins-datadog-plugin#130]
I'd like to see pipeline statistics as mentioned in [this blog post](https://stelligent.com/2017/11/16/codepipeline-dashboard/)

Each `Job` should provide
- Lead Time
- Cycle Time
- Feedback Time
- MTTR
- MTBF

![Fail 1](https://github.com/stelligent/pipeline-dashboard/blob/master/docs/pipeline-dashboard-fail-1.png?raw=true)

From [https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details](https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details)

What do you think, is it worth to start a PR?

**Comment by nmuesch** [comment]
Hey @pgarbe I'm gonna go ahead and close this since we just merged in the work from your PR https://github.com/DataDog/jenkins-datadog-plugin/pull/156 Thanks again for the issue report and the work on adding this functionality!

**Comment by pgarbe** [comment]
Thanks @nmuesch for finalising my work!
