### ISSUE TITLE
Unable to configure plugin for https://app.datadoghq.eu

### ISSUE THREAD

**Issue by gfelbing** [DataDog/jenkins-datadog-plugin#133]
It is not possible to push metrics to datadog.eu.

It seems that the URL is hard-coded here: https://github.com/DataDog/jenkins-datadog-plugin/blob/4f12a7d76076cec69fee48ef1a78d140570b6eae/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L420

**Comment by sjenriquez** [comment]
Hi @gfelbing , thanks for reaching out. There is an option to set the `Target API URL` under:

Manage Jenkins -> Configure System -> Datadog Plugin -> Advanced... (button bottom right)the Data

I'm going to close this issue, but if you run in to any problems with this please reach out to us at support@datadoghq.com, thanks!
