### ISSUE TITLE
Doesn't work with the EU environment

### ISSUE THREAD

**Issue by jldork** [DataDog/jenkins-datadog-plugin#141]
Hi all!

Trying to set up Jenkins in the app.datadoghq.eu site and pasted in the API key into my jenkins instance.
![image](https://user-images.githubusercontent.com/1771806/52011967-60949780-24a7-11e9-9d18-495aa1d799dc.png)

We're likely defaulting the API to the .com website

**Comment by sjenriquez** [comment]
Hi @jldork , you are correct, we use the .com website by default. However, this is configurable if you click the "Advanced" button under the Manage Jenkins > Configure System > Datadog > Advanced

https://d2ddoduugvun08.cloudfront.net/items/0L2I01402p2t0e09140Q/Screen%20Shot%202019-03-15%20at%2011.28.59%20AM.png?X-CloudApp-Visitor-Id=f61030341a5cdeeabebb404f73a53f77&v=13852d52
