### ISSUE TITLE
Adding Build Parameters as Tags

### ISSUE THREAD

**Issue by nrmitchi** [DataDog/jenkins-datadog-plugin#147]
I'm trying to add job parameters as build tags. It appears that this functionality was introduced in #38 , however since then, it looks that the ability to use job build parameters/environment variables as tags was removed, and instead limited to only groupings from the job name. 

See https://github.com/DataDog/jenkins-datadog-plugin/blob/46b025d16bb1b8725664aa0f822a77ded5b2d592/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java#L133

Side note, it seems that only up to 9 groupings are supported, at which point it will just loop back around, since it's only using the first character (which is assumed to be an int).

Overall, is there currently any way to include a build parameter as a job tag?

**Comment by gzussa** [comment]
I just a pretty big refactoring (merged on master branch) and at this point all the above feature seems to work fine. You can use env variables in your job using both properties below:
- `Add tags from file in workspace`
- `Add tags from list of properties`

The `globalTags` property doesn't support env variables (i don't think it even did) but it indeed uses regex. Regarding the grouping up to 9 issues, I am able to use 12.

Let me know if it still doesn't work for you.

I will make a release and keep you updated here

**Comment by gzussa** [comment]
We just release version [1.0.0](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-1.0.0). This is a major bump with backward incompatibility changes. See related [changelog](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/CHANGELOG.md#100--01-07-2020).
