### ISSUE TITLE
Ability to collect/push Jenkins Metrics plugins metrics to DataDog

### ISSUE THREAD

**Issue by mpailloncy** [DataDog/jenkins-datadog-plugin#148]
The [Metrics plugin](https://github.com/jenkinsci/metrics-plugin) provides a lot of Jenkins related metrics which could be very useful to have in DataDog.

Some random thoughts:

- The dependency between DataDog plugin and Metrics could be optional: DataDog plugin could collect/push metrics only if Metrics plugin is installed
- A field in the DataDog configuration could enable/disable this capability
- It's probably required to enforce usage of dogstatsd in this case (as there is a bunch of metrics)
- Could be interesting to provide a way to only push a subset of the metrics provided by the Metrics plugin

**Comment by mpailloncy** [comment]
I'm wondering if it's not better to create a dedicated plugin, WDYT?

**Comment by sjenriquez** [comment]
Hey @mpailloncy it may be better for the Metrics plugin to add Datadog support like they [do for Graphite](https://metrics.dropwizard.io/4.0.0/manual/graphite.html). The metrics appear to be in the statsd format already, it may not be too difficult to add support for a Datadog agent installed on the Jenkins master.

**Comment by mpailloncy** [comment]
Okay, so you're suggesting a dedicated plugin like https://github.com/jenkinsci/metrics-graphite-plugin right?

**Comment by sjenriquez** [comment]
Hey again @mpailloncy, I did some more digging and found a Datadog reporter listed on Dropwizard's [Third Party Libraries page](https://metrics.dropwizard.io/4.0.0/manual/third-party.html) 😃 . Check out the repo here, [coursera metrics-datadog](https://github.com/coursera/metrics-datadog).

**Comment by mpailloncy** [comment]
Hi @sjenriquez, I did some experiments and that seems to work as expected (all metrics pushed to DataDog, without a lot of effort). I'll continue to experiment and keep you inform here.

The only downside I found yet is that some metrics overlap: like _jenkins.queue.size_ (this plugin) and _jenkins.queue.size.value_ (coming from Metrics plugin) for example

**Comment by sjenriquez** [comment]
@mpailloncy Glad to hear you got that plugin working without much effort. While our Jenkins plugin does not have custom metric name prefixing, the coursera/Dropwizard plugin does have this option. This could be a workaround to prevent duplicate metric naming. I'm going to close this issue out, but please feel free to reply or reach out to support@datadoghq.com if you have an further questions. Thanks!

**Comment by mpailloncy** [comment]
Hi @sjenriquez, FYI the plugin is now hosted on jenkinsci org and a first version has been released: https://github.com/jenkinsci/metrics-datadog-plugin
