### ISSUE TITLE
Question: Move this repo under https://github.com/jenkinsci?

### ISSUE THREAD

**Issue by mpailloncy** [DataDog/jenkins-datadog-plugin#149]
Out of curiosity, is there a specific reason why this repo is not under jenkinsci organization?
See https://jenkins.io/doc/developer/publishing/requesting-hosting/

**Comment by sjenriquez** [comment]
Hey @mpailloncy There is a repo under the jenkinsci organization here https://github.com/jenkinsci/datadog-plugin/

Is that what you're referring to?

**Comment by mpailloncy** [comment]
ah right! 
Didn't realized that it was also under jenkinsci as [the wiki](https://wiki.jenkins.io/display/JENKINS/Datadog+Plugin) is pointing out to this repository.

**Comment by sjenriquez** [comment]
👍
