### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by ali11011** [DataDog/jenkins-datadog-plugin#151]
what about integrating the console and node output to datadog logs?

**Comment by gzussa** [comment]
@ali11011 We are currently working on pushing console logs to Datadog - https://github.com/DataDog/jenkins-datadog-plugin/pull/171. As for node logs, I don't think we can get them from the Jenkins plugin. You will have to install the Datadog agent on slave node to them.

**Comment by gzussa** [comment]
We are planning on adding logs very soon. Also, we are in the process of kill this repo in favor of https://github.com/jenkinsci/datadog-plugin. Closing this issue. For other feature requests, we recommend to contact our support team.
