### ISSUE TITLE
Pipeline build - add contextual tags

### ISSUE THREAD

**Issue by ali11011** [DataDog/jenkins-datadog-plugin#152]
Hi,

is it possible to push a tag value from the build pipeline jenkins file.

i have a set of standard reason codes for for build failures. In the jenkins file, in the catch block, i want to push this reason code to datadog using a "secondary_result" tag to compliment the result tag value.

is this possible?

Alistair

**Comment by nmuesch** [comment]
Hey @ali11011 I don't believe this is currently possible today. Are you looking for something similar to this - https://github.com/DataDog/jenkins-datadog-plugin/pull/144 ?

**Comment by ali11011** [comment]
i found a way to do this in the end, it isnt ideal but it works well enough for what we need

**Comment by awesinine** [comment]
@ali11011 : care to share?!?!?!?!  <3

**Comment by gzussa** [comment]
@ali11011 Sorry for the long delay here. I would love to help here. 

In order to be sure I understand your problem. Would you be able to provide me with a simple jenkin file example that I could use to reproduce your scenario?

**Comment by gzussa** [comment]
@ali11011 should I close this issue?

**Comment by gzussa** [comment]
Related https://github.com/DataDog/jenkins-datadog-plugin/pull/144

**Comment by gzussa** [comment]
We will track this as part of https://github.com/DataDog/jenkins-datadog-plugin/issues/115
