### ISSUE TITLE
Latest changes tag and version created

### ISSUE THREAD

**Issue by srizzling** [DataDog/jenkins-datadog-plugin#158]
Hi, with the new PR #132  being merged, is it possible to create a release for it.

**Comment by gzussa** [comment]
Hi, Thanks for opening this issue. I had to make some improvements to changes you mentioned. See https://github.com/DataDog/jenkins-datadog-plugin/pull/169. I will make a release with all included changes. I will keep this issue open until it is out.

**Comment by srizzling** [comment]
Hey @gzussa, whats used instead of Dogstatsd here?

**Comment by gzussa** [comment]
I am actually working on adding Dogstatsd back.
So you will be able to either use Datadog HTTP endpoints or DogStatD.

**Comment by gzussa** [comment]
We just release version [1.0.0](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-1.0.0). This is a major bump with backward incompatibility changes. See related [changelog](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/CHANGELOG.md#100--01-07-2020). As a consequence i closing this issue.
