### ISSUE TITLE
Can not see all the metrics e.g. jenkins.job.leadtime

### ISSUE THREAD

**Issue by faizan80** [DataDog/jenkins-datadog-plugin#162]
Hi,
I have a Jenkins running in a docker container.
I started the datadog agent docker on the same host as jenkins docker.
I executed couple of dummy jobs and still do not see any of the following metrics.

jenkins.job.leadtime
jenkins.job.cycletime 
jenkins.job.mttr
jenkins.job.feedbacktime
jenkins.job.mtbf

Am I doing something wrong ?
+
I am using the trial account.

**Comment by jeremy-lq** [comment]
@faizan80, we'll need some additional information to assist. Can you open a support ticket and we'll take it from there? Thanks.
https://docs.datadoghq.com/help/
