### ISSUE TITLE
Plugin does not compute KPI metrics

### ISSUE THREAD

**Issue by asrao-pv** [DataDog/jenkins-datadog-plugin#166]
# Plugin does not compute or send all KPI metrics

## Expected behavior
When there is a Datadog agent running on the machine running Jenkins, that agent should be sending the Jobs Completed, MTTR, MTBF, and other metrics to my Datadog account.

## Actual behavior
The agent sends the Jobs Completed metric but not others to my Datadog account.

## Relevant logs from plugin

```
API call of type 'v1/check_run' was sent successfully!
Oct 24, 2019 2:51:02 PM FINER org.datadog.jenkins.plugins.datadog.DatadogHttpRequests

Payload: {"check":"jenkins.job.status","host_name":"my-jenkins-app","timestamp":1571928662,"status":2,"tags":["job:my-job","node:master"]}
Oct 24, 2019 2:51:02 PM FINE org.datadog.jenkins.plugins.datadog.DatadogBuildListener

Sending 'completed' counter to localhost:8125 
Oct 24, 2019 2:51:02 PM FINE org.datadog.jenkins.plugins.datadog.DatadogBuildListener

Attempted to send 'completed' counter with tags: [job:my-job, node:master, result:FAILURE]
Oct 24, 2019 2:51:03 PM FINE org.datadog.jenkins.plugins.datadog.DatadogBuildListener

Finished onCompleted()
Oct 24, 2019 2:51:15 PM FINE org.datadog.jenkins.plugins.datadog.DatadogQueueListener

doRun called: Computing queue metrics
Oct 24, 2019 2:51:15 PM FINE org.datadog.jenkins.plugins.datadog.DatadogSCMListener

Using hostname set in 'Manage Plugins'. Hostname: my-jenkins-app
Oct 24, 2019 2:51:15 PM FINE org.datadog.jenkins.plugins.datadog.DatadogQueueListener

Resulting payload: {"series":[{"metric":"jenkins.queue.size","points":[[1571928675,0]],"type":"gauge","host":"my-jenkins-app"}]}
Oct 24, 2019 2:51:15 PM FINER org.datadog.jenkins.plugins.datadog.DatadogHttpRequests
```

## Observations from logs
In [DatadogBuildListener](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L197), after logging "Attempted to send 'completed' counter with tags:", it is supposed to log "Computing KPI metrics".

However, in the logs I get from the plugin, I don't see it attempting to compute the KPI metics.

This corresponds with the fact that in my datadog account I can see the following metrics:

- `jenkins.job.completed`
- `jenkins.job.duration`
- `jenkins.job.waiting`
- `jenkins.queue.size`

But I can't see those relating to MTTR or MTBF.

## Versions
**Jenkins:** 2.199
**Jenkins Datadog Plugin:** 0.7.1
**Datadog Agent:** 6.14.1
**OS:** Amazon Linux 2.0.20190618

**Comment by jeremy-lq** [comment]
@asrao-pv Thanks for bringing this to our attention. Can you please open a [support ticket](https://docs.datadoghq.com/help/) so we can properly track this feature request? Thanks.

**Comment by asrao-pv** [comment]
I've opened a support ticket. I'll try to update this issue with anything useful.
