### ISSUE TITLE
Datadoghq.eu support

### ISSUE THREAD

**Issue by davidjaquier** [DataDog/jenkins-datadog-plugin#167]
Hi!

Is it possible to add a configuration field to be able to use https://app.datadoghq.eu endpoint instead of the hardcoded 

private String targetMetricURL = "https://api.datadoghq.com/api/";

It could be really appreciated.

**Comment by asrao-pv** [comment]
If I understand your questions correctly you should be able to change the value of the `targetMetricURL` in the Jenkins system configuration:

Jenkins dashboard -> Manage Jenkins -> Configure System -> Datadog Plugin -> Advanced -> Target API URL

**Comment by davidjaquier** [comment]
Yep exact!

Because datadog provides this host to store data in Europe only...

**Comment by jeremy-lq** [comment]
@davidjaquier To confirm, if you are in the Datadog EU site, https://api.datadoghq.eu/api/ can be used for API calls. If you have any additional questions, if you open a ticket someone can walk you through the configuration.
