### ISSUE TITLE
Question about whitelist multibranch pipeline

### ISSUE THREAD

**Issue by fahmisdk6** [DataDog/jenkins-datadog-plugin#168]
I want to track some of my multibranch pipeline job. but i'm not sure how to write the job name in the Whilelist box of Jenkins Configuration Page. I tried to type only the job name (ex: `Android PR Checker`)or with pr-number (ex: `Android PR Checker/pr-111`) but then no jobs is tracked to datadog.

So, How to write the whitelist job properly for multibranch pipeline job?

I also try to filter jobs by adding tags, i add this line to `Global Jobs Tags`
`Android PR Checker(*?), owner:adx`
But i don't know how to use the tag to set filter inside the datadog dashboard.

**Comment by jeremy-lq** [comment]
@fahmisdk6 Please open a [support ticket](https://docs.datadoghq.com/help/) and someone will walk you through this.
