### ISSUE TITLE
Thread leak

### ISSUE THREAD

**Issue by jglick** [DataDog/jenkins-datadog-plugin#170]
An instrumented boot classpath revealed a mistake in this plugin that can cause thread leaks. See https://github.com/jenkinsci/datadog-plugin/pull/9 for the fix.

**Comment by gzussa** [comment]
Hi @jglick Thanks for opening this issue. I am currently working on some big refactoring and I included it as part of it. See https://github.com/DataDog/jenkins-datadog-plugin/pull/169. I keep this issue open until I make a new release.

**Comment by jglick** [comment]
Note that for plugins hosted on the Jenkins update center, we urge maintainers to do development in, and cut releases out of, the repository in @jenkinsci and in fact to delete any original clone. [Recent discussion](https://groups.google.com/d/msg/jenkinsci-dev/ykKUGJ7zZEQ/KBp6C_0fAgAJ)

**Comment by gzussa** [comment]
Thanks for the feedback, we are currently in the process of getting rid of this fork.
