### ISSUE TITLE
I can not see all the metrics, including some basic metrics like "jenkins.job.completed" and "jenkins.job.started"

### ISSUE THREAD

**Issue by provcristianmaluenda** [DataDog/jenkins-datadog-plugin#188]
I build this plugin and installed it in my Jenkins (0.7.2-SNAPSHOT ), and I can not see these metrics:

Metric | Description | Default Tag
-- | -- | --
jenkins.job.completed | Rate of completed jobs. | branch, job, node, result
jenkins.job.cycletime | Build Cycle Time. | branch, job, node, result
jenkins.job.duration | Build duration (in seconds). | branch, job, node, result
jenkins.job.feedbacktime | Feedback time from code commit to job failure. | branch, job, node, result
jenkins.job.leadtime | Build Lead Time. | branch, job, node, result
jenkins.job.mtbf | MTBF, time between last successful job and current failed job. | branch, job, node, result
jenkins.job.mttr | MTTR: time between last failed job and current successful job. | branch, job, node, result
jenkins.job.started | Rate of started jobs. | branch, job, node
jenkins.job.waiting | Time spent waiting for job to run (in milliseconds). | branch, job, node

Only are available this `jenkins.job.aborted`.

I using the Datadog's API to report to Datadog. Should I use DogStatsD instead?

Regards,
Cristian

**Comment by provcristianmaluenda** [comment]
I think my issue is I need to add my job to the whitelist. Why do I need to do that? If I want metrics for all my job, why should I use whitelist?

**Comment by jeremy-lq** [comment]
@provcristianmaluenda 
We need some additional information to assist. Please open a support ticket and we'll pick the issue up from there. Thanks.
