### ISSUE TITLE
Nullpointer when onStarted/onCompleted call the method "getBuildTags"

### ISSUE THREAD

**Issue by provcristianmaluenda** [DataDog/jenkins-datadog-plugin#191]
**Describe the bug**
The current version doesn't send all the metrics to Datadog. The reason is a null pointer exception.

Debugging a little bit, there is a null pointer [here](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java#L84)

My configuration is:
* Datadog API URL: `https://api.datadoghq.com/api/`
* Datadog API KEY: `XXXXXX`
* Global Tags: `env:test`
* Global Job Tags: `env:test`
* Send Security audit events: `true`
* Send System events: `true`

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
1. Pull last changes from master (Using this [commit](https://github.com/DataDog/jenkins-datadog-plugin/commit/2d5c4a311afbd82b4f4b2cb8b94e0f03d90cced1))
2. Add logs to the code
3. Build the project using Java 8 and mvn. My build is [here](https://github.com/providenceinnovation/jenkins-datadog-plugin/releases/tag/test)
4. Deploy Jenkins on Kubernetes using Jenkins' helm chart and CasC plugin
5. Check the logs:
```
2020-01-03 23:21:55.610+0000 [id=163]	WARNING	o.d.j.p.datadog.DatadogUtilities#getBuildTags: Starting debugging
2020-01-03 23:21:55.610+0000 [id=163]	WARNING	o.d.j.p.datadog.DatadogUtilities#getBuildTags: jobname: devex/jenkins-test/master
2020-01-03 23:21:55.610+0000 [id=163]	WARNING	o.d.j.p.datadog.DatadogUtilities#getBuildTags: GlobalJobTags: (.*?), env:test
2020-01-03 23:21:55.611+0000 [id=163]	WARNING	o.d.j.p.datadog.DatadogUtilities#getBuildTags: DatadogJobProperty: null
```

**Expected behavior**
I should be able to see the metrics on Datadog for the jobs.

**Environment and Versions (please complete the following information):**
Jenkins System info [here](https://github.com/providenceinnovation/jenkins-datadog-plugin/releases/download/test/jenkins.Configuration.pdf)

**Comment by gzussa** [comment]
Hi @provcristianmaluenda. Thanks for reporting this issue. I will take a look at it ASAP.

**Comment by gzussa** [comment]
So I tried to reproduce the error and i am not able to do so. Here is what i did. Maybe you can help me troubleshoot this.

- I pulled the latest from this repo.
- Run `mvn install`. To verify that tests pass and to install the plugin on my local maven cache.
- Create a `JENKINS_PLUGIN` env variable pointing to your project repo `export JENKINS_PLUGIN=PATH_TO_/DataDog/jenkins-datadog-plugin`
- Use `docker-compose  up` to spin up Jenkins with the following `docker-compose.yaml`
```
  version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - $JENKINS_PLUGIN/target/:/var/jenkins_home/plugins
    environment:
      - DATADOG_JENKINS_PLUGIN_TARGET_API_KEY=XXXXXXX
```
- Configure Jenkins, install plugins (none), create user account, restart
- Log back in, Configure the plugin like you mentioned it in the description.
- Create a job (freestyle) with a shell script as explained in [here](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/DEVELOPMENT.md#create-your-first-job).
- Run the job and check log and in DD if metrics are reported.

Again everything works for me so I will need more details. Thanks

**Comment by provcristianmaluenda** [comment]
Thanks @gzussa for your update. I will test it this weekend.

**Comment by provcristianmaluenda** [comment]
Thanks for the fix!
