### ISSUE TITLE
DatadogUtilities.getDatadogJobProperties returned null value that get dereferenced later on

### ISSUE THREAD

**Issue by dgounaris** [DataDog/jenkins-datadog-plugin#196]
**Describe the bug**
When trying to apply this plugin on some jenkins jobs (still haven't identified their unique circumstances), there were null pointers thrown on `DatadogBuildListener.onStarted` and `DatadogBuildListener.onComplete`. These caused the relevant graphs to not display jobs properly, as there were no events registered for them. Other, intermediate, messages were successfully appearing on the datadog dashboard event stream. These were consistent, meaning that a job either always threw these exceptions or always did not.

After further investigation, it seems that `DatadogUtilities.getDatadoJobProperties` may return null, a result which is dereferenced later on in the code. A proposed fix would be to return a fresh `DatadogJobProperty` instead, as the inner parameters have sane default initializations within the object. 

Proposed fix pr is here #197.

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
Create a jenkins pipeline job before installing the datadog plugin. Install the plugin, but do not alter the configuration of the jenkins job. The job events should not fire normally to datadog. Then, edit and save the configuration (no changes are actually required). The events should fire as normal.

**Expected behavior**
I should expect to see the started/completed messages and the relevant graphs on my datadog dashboard, along with logs stating that onStarted and onCompleted completed successfully locally.

**Screenshots**
<img width="1259" alt="Screenshot 2020-01-21 at 11 25 32" src="https://user-images.githubusercontent.com/17044221/72801186-dd80ca00-3c40-11ea-9fb5-777610261c67.png">

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - Datadog plugin 1.0.0
  - Jenkins 2.204.1 and 2.190.3

**Additional context**

**Comment by dgounaris** [comment]
I think I found the root cause. On existing jobs, DatadogJobProperties is null when datadog is setup after their creation and their configuration has not changed. Saving the configuration once manually after installing the plugin resolves the issue and the job properly shows itself on the datadog dashboard.

**Comment by gzussa** [comment]
Hi @dgounaris, this issue should be fixed as part of release 1.0.1.
See https://github.com/DataDog/jenkins-datadog-plugin/issues/191
