### ISSUE TITLE
Enable reduce log level of datadog plugin

### ISSUE THREAD

**Issue by pablorf-dev** [DataDog/jenkins-datadog-plugin#22]
Currently, Datadog logs a lot of information before and after the job starts, prefixed with DatadogBuildListener.java:.

Would be nice to be able to reduce or suppress that logging using an option in the plugin.

**Comment by dmabamboo** [comment]
Agree, and using PrintStream it makes it painful to manage log levels and such. I'd propose using JUL which can be more finely managed from within Jenkins. I've created a pull request for your 0.2.0 version which got never merged by I'll do the same again against your 0.3.0 version and make another pull request to see if it comes through.

**Comment by JohnLZeller** [comment]
Merged @dmabamboo's PR (https://github.com/DataDog/jenkins-datadog-plugin/pull/29) to solve this. Thanks!
