### ISSUE TITLE
Plugin does not seem to respect proxy settings

### ISSUE THREAD

**Issue by tombry** [DataDog/jenkins-datadog-plugin#26]
We run our Jenkins v1.596 server in a lab that lives behind proxies.  From the CLI, replacing real values with dummy values here, I can successfully run 

export http_proxy=http://myproxy.foo.com:80/
export https_proxy=http://myproxy.foo.com:80/
wget https://app.datadoghq.com/api/v1/validate?api_key=1234key

The wget completes in just a second and returns the following body content: {"valid": true}

But when I run a Jenkins job, the plugin just hangs and then times out (after several minutes) with output like this, and we never see events in our DataDog dashboard

DatadogBuildListener.java: Started build!
DatadogBuildListener.java: Using hostname set in 'Manage Plugins'. Hostname: myhostname.foo.com
DatadogBuildListener.java: Sending event

Similarly, in the Manage Jenkins > Configure System page, we have the same proxies set in the Global properties section.  In the Datadog Plugin, when I enter my key and click "Test", it spins for a while and then gives me "ERROR".  

I also tried adding the following arguments to the CLI where I launch Jenkins:  -Dhttp.proxyHost=myproxy.foo.com -Dhtttps.proxyHost=myproxy.foo.com -Dhttps.proxyPort=80

Same (bad) behavior from the plugin.

From a general Java perspective, these links may be useful: http://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html and http://stackoverflow.com/questions/2430142/java-app-behind-proxy-to-use-http-proxy-variable-in-linux.  But I've never written a Jenkins plugin before, so I'm not sure whether there's anything special the plugin needs to do to pick up the proxy settings.

**Comment by tombry** [comment]
Correction.  The proxy settings *do* seem to work if I use the defines on the Java CLI for Jenkins.  As you can see above, I had a misspelling: htttps.proxyHost instead of https.proxyHost.

Still, it would be nice if the plugin would simply use the settings in the Manage Jenkins > Configure System page's Global Properties section, assuming that we've configured http_proxy and https_proxy environment variables there.

**Comment by JohnLZeller** [comment]
@tombry we have added proxy support to the plugin and you'll see it available in the next release.

PR is here: https://github.com/DataDog/jenkins-datadog-plugin/pull/30
