### ISSUE TITLE
Merge dd-agent's tags into the emitted metrics

### ISSUE THREAD

**Issue by jshirley** [DataDog/jenkins-datadog-plugin#32]
I'll start by describing what I want to accomplish first, then suggested fix.

We have two Jenkins clusters, one for QA and one for Prod, and want to separate alerts out based on this environment. The `/etc/dd-agent/datadog.conf` has this, and is managed through our automation. 

The Jenkins plugin, however, does not try to integrate those configured tags. Events emitted by the Jenkins plugin have a fixed set of tags. The old Jenkins integration that parsed `build.xml` went through the local collector and didn't have this limitation.

Is it feasible to pull the tags from the local agent (if available) and merge those in? Either by checking for the file on disk, parsing and extracting `tags:` or an action against the agent API?

We're happy to contribute patches to resolve this issue with some guidance.

Thanks!

**Comment by JohnLZeller** [comment]
Hey @jshirley, thanks for the ticket :)

You're right that tags are currently static on the Jenkins plugin, but I'm looking at adding custom tagging per job, which should enable some flexibility. In terms of being able to separate out alerts by QA and Prod, in your case, this seems like it's best fit for the hostname tag. Currently the Jenkins plugin determines the hostname tag by looking, in order, at the Jenkins configuration (plugin specific), the Jenkins hostname environment variable, the Unix hostname via `/bin/hostname -f`, and finally the Localhost hostname.

If you make sure that the hostname in the agents `datadog.conf`, and the hostname used by the Jenkins plugin are the same, you'll be able to keep Jenkins metrics with the other metrics coming from the agent on the same host.

It's also worth nothing that we're deprecating the old Jenkins check that went through the agent, in favor of this Jenkins plugin.

**Comment by JohnLZeller** [comment]
I'm going to close this ticket for now, but please feel free to comment back with more info

**Comment by jshirley** [comment]
The hostname isn't sufficient in our cases for the environment, the environment isolation means that we rely on a separate tag that is in the `tags:` section in the agent configuration. We don't really keep any persistent meaning on a per-hostname basis, and instead have a fixed `host_env` tag that makes this much easier.

**Comment by remh** [comment]
@jshirley what @JohnLZeller meant is that, if your agent hostname and jenkins configuration have the same "hostname", the tags set in your datadog.conf will be automatically applied to your jenkins metrics as we'll merge that in the backend.

You should just make sure sure that your jenkins server have the same hostname as the agent hostname for those to combine.

**Comment by jshirley** [comment]
Ah! That's brilliant -- I realized now that we were seeing incorrect tagging but that was because we accidentally had both the legacy check that parses build.xml and the new plugin running.

Thanks so much!
