### ISSUE TITLE
Provide option to post to local dogstatsd rather than going directly to the API

### ISSUE THREAD

**Issue by gregsymons** [DataDog/jenkins-datadog-plugin#34]
On occasion I've had issues with posts to the API timing out and then "failing" what would have otherwise been a successful build. Since I'm generally running the agent somewhere nearby Jenkins anyway, it'd be nice to leverage that to have a little safety against hiccups in API availability.

**Comment by JohnLZeller** [comment]
Hey @gregsymons! Thanks for the ticket!

So I can understand your specific situation a bit better, could you clarify what happened? Your build "failed" when the plugin failed to post? Or, the plugin failed when it failed to post?

As far as posting to a dogstatsd somewhere. When we created the jenkins plugin, we deprecated a jenkins agent check. Introducing this option to send to a local dogstatsd could provide some safety, but I'm curious if it's the best option. I'm going to take a further look at this and get back to you here.

**Comment by gregsymons** [comment]
Unfortunately, I don't have any build output to show exactly what was happening--I disabled the plugin to keep things moving, and all the failed builds have been rotated into dust by now. But, what I remember is that the build would stall for a long time after logging the following:

```
DatadogBuildListener.java: Completed build!
DatadogBuildListener.java: Using hostname set in 'Manage Plugins'. Hostname: ci.gwfathom.com
DatadogBuildListener.java: Sending event
```
 and then would eventually timeout and throw an exception, which would change the build result to `FAILURE` even though the build itself was otherwise successful. It _may_ have been an interaction with the Workflow plugin, since the builds in question are Workflow builds, but I don't have any direct evidence of that.

**Comment by JohnLZeller** [comment]
@gregsymons I'm curious if you've run into more issues with this since your last comment. Could be a good use case to fire at DogStatsD if a none 200 response from the API occurs.

**Comment by mccutchen** [comment]
+1 for being able to configure this plugin to publish only to the local `dogstatsd` instance.  I see a couple significant benefits to that approach:
 - Jenkins no longer needs to know any DataDog API keys (simpler plugin configuration & one fewer way to leak secrets)
 - Metrics will automatically pick up host-level global tags (simpler plugin configuration & automatic tagging consistency with all other metrics recorded elsewhere in the infrastructure)

**Comment by JohnLZeller** [comment]
All valid points @mccutchen, I'll prioritize this. Thanks!
