### ISSUE TITLE
Handle jobs within folders properly (such as Multibranch Workflow)

### ISSUE THREAD

**Issue by rtyler** [DataDog/jenkins-datadog-plugin#35]
One of the features that's really starting to be used often is the [Workflow plugin](/jenkinsci/workflow-plugin), a part of that functionality is "Multibranch" ([explained here](https://jenkins-ci.org/blog/2015/12/03/pipeline-as-code-with-multibranch-workflows-in-jenkins/)) which creates a "Folder" with jobs in it for each branch which contains a `Jenkinsfile` ([example of such a job here](https://ci.jenkins-ci.org/view/Infrastructure/job/jenkins.io/)).

When the plugin reports job statistics it is only reporting the job name, which means that all "Workflow Multibranch" or any other jobs within Folders which share the same name will be largely indistinguishable inside of the Datadog UI.

![master-event](https://cloud.githubusercontent.com/assets/26594/12273958/6f176538-b91d-11e5-9913-33e9847fc8d3.png)

This is particularly problematic if one wants to set up a monitor based on a specific job failing :(

**Comment by JohnLZeller** [comment]
Thanks @rtyler! This definitely deserves to be looked at closer. I'm going to go ahead and prioritize this for a next release.

**Comment by ysoldak** [comment]
This can be reduced to two jobs with the same name, placed into different folders.
Full names of the jobs in this case: `folder1/jobname` and `folder2/jobname`.

**Comment by witokondoria** [comment]
Maybe replacing getDisplayName() usage for getFullName() at [onStarted](https://github.com/DataDog/jenkins-datadog-plugin/blob/master/src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java#L92) method would make this?

According to its [javadoc](http://javadoc.jenkins-ci.org/hudson/model/AbstractItem.html#getFullName()), it seems so.

**Comment by JohnLZeller** [comment]
Solved in #68 and #77

**Comment by witokondoria** [comment]
@JohnLZeller could this changes be moved to jenkinsci/datadog-plugin and proceed with a release (even with a small set of changes)?  Its been more than a month since last one

**Comment by JohnLZeller** [comment]
Hey @witokondoria! Sorry for the delay on that. I left Datadog last month, so this will have to fall to another engineer there. @remh could we have someone pick this up?

**Comment by remh** [comment]
Thanks for the feedback! @sjenriquez can you have a look please ?
