### ISSUE TITLE
tags for releases?

### ISSUE THREAD

**Issue by nrvale0** [DataDog/jenkins-datadog-plugin#37]
Any chance we could get tags for the release changeset ids for the last couple of releases? Would make it easier for those who have to git clone && git checkout releases.

thx!

**Comment by JohnLZeller** [comment]
Hey @nrvale0! Sure thing, I'll get this added and report back here once that has been done.

**Comment by nrvale0** [comment]
Sounds good. Thx!

**Comment by JohnLZeller** [comment]
So, this repository is used for ongoing development of the plugin, and releases get pushed to the plugin repo hosted in the [jenkinsci](https://github.com/jenkinsci) account. You can find the release tags here:
https://github.com/jenkinsci/datadog-plugin/releases

Let me know if you have any more questions :)
