### ISSUE TITLE
Add project name as a tag

### ISSUE THREAD

**Issue by acasademont** [DataDog/jenkins-datadog-plugin#40]
As discussed in #38 it would be useful to have a the project tag name to be able to group jobs belonging to the same jenkins project and therefore create more meaningful alerts.

I'll try to work on a patch

**Comment by JohnLZeller** [comment]
Hey @acasademont, thanks for the issue ticket! :)

Definitely seems like a use case we want to support. Let me know if you run into any hurdles

**Comment by sjenriquez** [comment]
Hi @kjbro, it's not something we'll be working on in the immediate future, but feel free to submit a PR if you get started before we do. Thanks!

**Comment by gzussa** [comment]
Hi, I believe this is fixed since submit the job tag. Maybe I am not understand what the difference is between a Job name and a project name. Both terms are used interchangeably in Jenkins doc.
Closing this for now. Feel free to reopen with more details.
