### ISSUE TITLE
Add service check when a job is running

### ISSUE THREAD

**Issue by acasademont** [DataDog/jenkins-datadog-plugin#41]
Hi! We think it would also be useful to report a service check when the job is currently running, so we can monitor that too in our dashboard. Main problem is, what status should it emit? AFAIK there only 4 possible statuses and I'm not sure if a "Running Job" would better qualify as a WARNING or UNKNOWN, I'm not 100% happy with any of them, opinions?

**Comment by JohnLZeller** [comment]
Hey @acasademont! You can actually set up a monitor based on an event, which might be a good way to obtain this functionality. I'm not sure that a service check is the best way to capture this info. Let me know if using the events on a monitor works for your use case.

**Comment by JohnLZeller** [comment]
I'll close this for now, but let me know if this resolves things.

**Comment by acasademont** [comment]
HI @JohnLZeller, I thing you might be right but at the moment I don't know how to set up a simple "color box" (aka service check dashboard widget) that shows me the last status of a given job in jenkins.

Even if I ignore the "running job" thing I don't know how to do it, as the job status is reported as a tag (maybe that's the problem?) and I can't create a check on a given job.

<img width="407" alt="screen shot 2016-04-15 at 17 17 36" src="https://cloud.githubusercontent.com/assets/825021/14566020/0b324ae6-032e-11e6-8420-1d4d34581e09.png">

As you can see I am unable to create a single check on a given job due to the "status" tag (which is a different thing than the status of the check)
