### ISSUE TITLE
java NPE exception 

### ISSUE THREAD

**Issue by vchan2002** [DataDog/jenkins-datadog-plugin#45]
This appears to be a new issue that seems to have shown up after the upgrade of the datadog plugin to version .5

A lot of our jenkins job now crashes right at a beginning, with a NPE exception....

java.io.IOException: java.lang.NullPointerException
16:53:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:614)
16:53:52 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
16:53:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
16:53:52 	at hudson.model.Run.execute(Run.java:1738)
16:53:52 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:53:52 	at hudson.model.ResourceController.execute(ResourceController.java:98)
16:53:52 	at hudson.model.Executor.run(Executor.java:410)
16:53:52 Caused by: java.lang.NullPointerException
16:53:52 	at org.datadog.jenkins.plugins.datadog.DatadogSCMListener.onCheckout(DatadogSCMListener.java:47)
16:53:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:612)

Unfortunately, this is causing a lot of our jobs to be unusable.....

**Comment by jmellor** [comment]
I have that same traceback.  I uninstalled the datadog plugin in order to workaround the problem.

**Comment by JohnLZeller** [comment]
This is being fixed by #44, and a bugfix release is forthcoming. Sorry for the hassle!

**Comment by JohnLZeller** [comment]
Fix released in [0.5.1](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-0.5.1). Should be public on all mirrors in ~4 hours
