### ISSUE TITLE
jenkins.job.duration is no longer emitted

### ISSUE THREAD

**Issue by doy** [DataDog/jenkins-datadog-plugin#50]
We upgraded from 0.4.1 to 0.5.2, and we no longer seem to be getting `jenkins.job.duration` metrics at all. I looked through the changes, but can't seem to see anything that would have obviously caused this. Is there anything I can do to look into this?

**Comment by JohnLZeller** [comment]
Hey @doy, thanks for your comment

There indeed wasn't anything that should have removed this metric, and we ourselves are using the most recent version of our plugin with no problems. Could you perhaps be seeing some errors in the logs for this plugin? [Here is a guide](https://github.com/DataDog/jenkins-datadog-plugin#logging) for how to gather this in Jenkins.

I'm gonna close this issue ticket for now, but please let me know what you find. And I encourage you to contact Datadog support by emailing support@datadoghq.com if you are unable to solve this, so we can get a higher bandwidth for troubleshooting.

**Comment by doy** [comment]
Looks like our Datadog API key was rolled at around the same time as I did the upgrade - sorry for the confusion!

**Comment by JohnLZeller** [comment]
No problem! I'm glad it was something simple like that :)
