### ISSUE TITLE
Support for Japanese Job Name

### ISSUE THREAD

**Issue by kitamurakei** [DataDog/jenkins-datadog-plugin#54]
Jenkins job name of Japanese will raise garbled character in Datadog.

Like this.
![image](https://cloud.githubusercontent.com/assets/5388202/17476108/3cf748d6-5d99-11e6-998c-adf188cdf0be.png)

There should be is this.
![image](https://cloud.githubusercontent.com/assets/5388202/17476135/65d17510-5d99-11e6-8cbd-b351cccdd34c.png)

**Comment by JohnLZeller** [comment]
Resolved with https://github.com/DataDog/jenkins-datadog-plugin/pull/63
