### ISSUE TITLE
Last release broke "passing/failing Jenkins jobs" in Jenkins dashboard

### ISSUE THREAD

**Issue by yannrouillard** [DataDog/jenkins-datadog-plugin#67]
Hi,

It seems the "results" tag is not anymore passed with `jenkins.job.status` because of a recent commit.
As a result we can't anymore count easily the number of failed and successful jobs and the two related widgets default dashboard jenkins don't work anymore.

Is it possible to add back the result tag or to have the appropriate metric to extract this information ?

Thanks in advance.

Yann

**Comment by sjenriquez** [comment]
Hi @yannrouillard, sorry for the delay getting back to you! I _think_ you're referring to the metric `jenkins.job.completed`. We merged a fix for this (#76) that went out with the last release, 0.5.6, a plugin update should resolve if you haven't done so already. Sorry again for the delay getting back to you!
