### ISSUE TITLE
Add option to add hostname

### ISSUE THREAD

**Issue by JohnLZeller** [DataDog/jenkins-datadog-plugin#7]
The agent currently has the option to allow adding a hostname in`datadog.conf`. Let's add this option to the configuration screen for the plugin as well.

**Comment by JohnLZeller** [comment]
+1 for this

**Comment by kbaltrinic** [comment]
Actually this seems to be presenting as a bug.  We have both the old agent and the new plugin running side-by-side for evaluation purposes and we are getting events like `soapui-tests succeeded on ci20-jen-001` from the agent and `soapui-tests build #112 succeeded on null` from the plugin.

We love that the new plugin provides some additional tags, but without mapping the event to a host, and hence to all of the host's tags, its actually a big step backwards.  Good work so far though.  These are just  details to be ironed out.

**Comment by JohnLZeller** [comment]
Thanks @kbaltrinic! I've updated the issue to a bug. We are aware of the host name issue presenting as `null` and will be doing another release of the plugin to fix the issue. And thanks for your other feedback as well! :) I'm glad you're liking the plugin. Looking forward to improving this plugin

**Comment by JohnLZeller** [comment]
PR #15 should handle this, and it has been merged and will be included in the 0.2.0 release (the next release)
