### ISSUE TITLE
jenkins.job.duration not tagged with tags inherited from AWS, datadog.conf, etc.

### ISSUE THREAD

**Issue by mrhota** [DataDog/jenkins-datadog-plugin#74]
I'd like jenkins.job.duration to have the tags that everything else coming out of my jenkins master does, but it seems to completely bypass the datadog agent (how else could it skirt those tags?)

**Comment by sjenriquez** [comment]
Hey @mrhota thanks for reaching out! #34 will make this possible, this won't make in to our next release, but I will be sure to include it in the following release (0.6.1). Thanks!
