### ISSUE TITLE
Allow the ability to constrain the jobs that are tracked

### ISSUE THREAD

**Issue by dbirtch-va** [DataDog/jenkins-datadog-plugin#79]
Use case: I only want to report on branches that can harm my production environment (ie. merges/deploys to branch "master") I'd like to whitelist those and have all others ignored. 

The current blacklist doesn't help as each team/feature branch has different naming and it doesn't scale. 

Blacklist feature added here: 
https://github.com/DataDog/jenkins-datadog-plugin/issues/6

**Comment by sjenriquez** [comment]
Hey @dbirtch-va, a whitelist option (#78) is going out with our next release!
