### ISSUE TITLE
datadog plugin impacting job performance

### ISSUE THREAD

**Issue by saurabhsingh39** [DataDog/jenkins-datadog-plugin#92]
As soon as we are installing this plugin into our Jenkins, any job takes around 2 minutes to start and after it gets start also performance remains slow through out the job flow. Job which usually takes 5 minutes to complete is taking more than double of that time.

**Comment by ssbarnea** [comment]
Wow, I am really curious about what kind of config issue you have because I enabled this plugin on high-use production instances with 500-3000 jobs each. The idea of having monitoring producing a DDOS is really scary. What version did you install?

**Comment by sjenriquez** [comment]
Hi @saurabhsingh39, we haven't had any reports of this, are you still seeing an issue? If so could you please reach out to support@datadogqh.com so we can help investigate?
